### ISSUE TITLE
FrizzyCraft test

### ISSUE THREAD

**Issue by Xgamings11X** [LoneDev6/addons-listing#10]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: FrizzyCraft
title: FrizzyCrafRPG
content: SurvivalRPG FrizzyCraft
premium: true
icon: https://imgur.com/UybMzdx
banner: imgurlUrlHere
time: 2025-01-01
links:
- https://minecraft-mp.com/server/341011/vote/
tags:
- items
- blocks
```
