### ISSUE TITLE
Premium Rank Pack | Total +69

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#11]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Premium Rank Pack | Total +69
content: +69 Chat Rank with ItemsAdder config
premium: true
icon: https://i.imgur.com/odsnOBR.png
banner: https://i.imgur.com/odsnOBR.png
time: 2025-04-21
links:
- https://builtbybit.com/resources/premium-rank-pack-total-69.64523/
tags:
- rank
- tag
- chat rank
```
