### ISSUE TITLE
Rank Pack with Icons | Total +56

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#12]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Rank Pack with Icons | Total +56
content: +56 Chat Rank with ItemsAdder config
premium: true
icon: https://i.imgur.com/qhoTD3g.png
banner: https://i.imgur.com/qhoTD3g.png
time: 2025-04-21
links:
- https://builtbybit.com/resources/rank-pack-with-icons-total-56.64520/
tags:
- rank
- tag
- chat rank
```
