### ISSUE TITLE
Farmer UI Template + Font

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#13]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Farmer UI Template + Font
content: GUI Templates | Total 10 GUI with ItemsAdder config
premium: true
icon: https://i.imgur.com/2RNDTFm.png
banner: https://i.imgur.com/2RNDTFm.png
time: 2025-04-21
links:
- https://builtbybit.com/resources/farmer-ui-template-font.64834/
tags:
- gui
- menu
- ui template
```
