### ISSUE TITLE
Solo Leveling UI Template & Containers

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#14]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Solo Leveling UI Template & Containers
content: GUI Templates & Containers | Total 29 GUI with ItemsAdder config
premium: true
icon: https://i.imgur.com/CZUh0qd.png
banner: https://i.imgur.com/CZUh0qd.png
time: 2025-04-21
links:
- https://builtbybit.com/resources/solo-leveling-ui-template-containers.64517/
tags:
- gui
- menu
- ui template
```
