### ISSUE TITLE
Solo Leveling ESC Menu

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#15]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Solo Leveling ESC Menu
content: Escape Menu with ItemsAdder config
premium: true
icon: https://i.imgur.com/AElGHaj.png
banner: https://i.imgur.com/AElGHaj.png
time: 2025-04-21
links:
- https://builtbybit.com/resources/solo-leveling-esc-menu.64457/
tags:
- esc menu
- pause menu
- escape menu
- pause ui
```
