### ISSUE TITLE
MAMAD11

### ISSUE THREAD

**Issue by MAMADkhan112** [LoneDev6/addons-listing#18]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: author
title: YourTitleHere
content: YourDescriptionHere
premium: false
icon: imgurlUrlHere
banner: imgurlUrlHere
time: 2025-01-01
links:
- https://spigotmc.org/resources/xxxxxx
- https://builtbybit.com/resources/xxxxxx
tags:
- items
- blocks
```
