### ISSUE TITLE
BetterEmojis

### ISSUE THREAD

**Issue by iReshoo** [LoneDev6/addons-listing#22]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Cruz
title: BetterEmojis
content: Adds 35+ brand new emojis for ItemsAdder!
premium: true
icon: https://cdn.discordapp.com/attachments/1162996187364872212/1365525539128872990/Thumbnail.png?ex=680da042&is=680c4ec2&hm=d50f17ed3faded8bf7f8ecc23c03422df1f093af6c44f2e1e4c47cd8a16d8c0b&
banner: https://cdn.discordapp.com/attachments/1162996187364872212/1365525154683289600/BannerGithub.png?ex=680d9fe7&is=680c4e67&hm=fcc9ed4e88d8729554bbb6f7e8eeccaf44b82578fbf9069671b09f12904f9df9&
time: 2025-04-25
links:
- https://polymart.org/product/4127/betteremojis-itemsadder-add-on
tags:
- emojis
```
