### ISSUE TITLE
Cute katanas

### ISSUE THREAD

**Issue by mowinge** [LoneDev6/addons-listing#23]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: lingemnow
title: Cute Katanas
content: Cute katanas with items adder config!
premium: true
icon: https://ibb.co/GvCmHJ0t
banner: https://ibb.co/GvCmHJ0t
time: 2025-05-08
links:
- https://builtbybit.com/resources/cute-katanas-for-minecraft.65335
tags:
- items
- tools
```
