### ISSUE TITLE
Desert Minecraft ESC Menu

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#24]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Desert Minecraft ESC Menu
content: FREE ItemsAdder Config!
premium: true
icon: https://i.imgur.com/LNTlra7.png
banner: https://i.imgur.com/LNTlra7.png
time: 2025-05-09
links:
- https://builtbybit.com/resources/desert-minecraft-esc-menu.66650/
tags:
- esc menu
- escape menu
- pause menu
- pause ui
```
