### ISSUE TITLE
Valorant ESC Menu

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#25]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Valorant ESC Menu
content: with ItemsAdder Config
premium: true
icon: https://i.imgur.com/0dWh6ZY.png
banner: https://i.imgur.com/0dWh6ZY.png
time: 2025-05-10
links:
- https://builtbybit.com/resources/valorant-minecraft-esc-menu.66720/
tags:
- esc menu
```
