### ISSUE TITLE
MoreFlags

### ISSUE THREAD

**Issue by iReshoo** [LoneDev6/addons-listing#27]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Cruz
title: MoreFlags
content: Display your players' nationalities directly in the TAB list and chat!
premium: true
icon: https://imgur.com/a/t3hJ6vB
banner: https://imgur.com/a/bo5t8sL
time: 2025-05-17
links:
- https://polymart.org/product/7814/moreflags-itemsadder-add-on
tags:
- TAB
- HUD
- FLAGS
```
