### ISSUE TITLE
Shien ESC Menu

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#28]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Shien ESC Menu
content: ItemsAdder config
premium: true
icon: https://i.imgur.com/tXrArZ0.png
banner: https://i.imgur.com/tXrArZ0.png
time: 2025-05-24
links:
- https://builtbybit.com/resources/shien-minecraft-esc-menu.67543/
tags:
- minecraft esc menu
- minecraft escape menu
```
