### ISSUE TITLE
Shien Minecraft UI Template + Font

### ISSUE THREAD

**Issue by Proomp** [LoneDev6/addons-listing#30]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: WellSetups
title: Shien Minecraft UI Template + Font
content: Total 9 GUI + ItemsAdder config file
premium: true
icon: https://i.imgur.com/tdZsA85.png
banner: https://i.imgur.com/tdZsA85.png
time: 2025-05-24
links:
- https://builtbybit.com/resources/shien-minecraft-ui-template-font.67593/
tags:
- items
- blocks
```
