### ISSUE TITLE
Cosmetics Pack

### ISSUE THREAD

**Issue by Timm137** [LoneDev6/addons-listing#32]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Timm255
title: Cosmetics Pack
content: cosmetic hats and decorations for minecraft server
premium: false
icon: https://i.imgur.com/JZcd4XI.png
banner: https://i.imgur.com/lbCbdGl.png
time: 29/05/2025
links:
- https://www.spigotmc.org/resources/addon-cosmetics-itemsadder-free.125529/
tags:
- HATS
```
