### ISSUE TITLE
World additions: Pebbles

### ISSUE THREAD

**Issue by Gu57-git** [LoneDev6/addons-listing#34]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Gust
title: World additions: Pebbles 
content: YourDescriptionHere
premium: false
icon: https://media.discordapp.net/attachments/1153931486161022986/1379425818819956746/pebbles_11.png?ex=684031e7&is=683ee067&hm=e984ca727f055bfafc589ad8107a493e94c0e5f41a7d06e4a042e0bfda61e3cc&=&format=webp&quality=lossless
banner: https://media.discordapp.net/attachments/1225413599963512892/1377967013275762740/image.png?ex=683f8089&is=683e2f09&hm=ffe816f2bf8a7834661f3c19c342f132d0e039009d2d5d3f82593bace9fe59cf&=&format=webp&quality=lossless&width=1207&height=562
time: 2025-06-03
links:
- https://www.spigotmc.org/resources/world-additions-pebbles.125679/
tags:
- items
- blocks
- World decorations
```
