### ISSUE TITLE
Star Wars At-Rt

### ISSUE THREAD

**Issue by Kuba1510** [LoneDev6/addons-listing#36]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Kuba1510
title: resource pack add new mob/entites At-Rt 
content: YourDescriptionHere
premium: false
icon: imgurlUrlHere
banner: imgurlUrlHere
time: 2025-09-06
links:
- https://www.spigotmc.org/resources/at-rt-itemsadder-addon.101729/
tags:
- entites
```
