### ISSUE TITLE
Builder's Lab

### ISSUE THREAD

**Issue by AlCraft-Network** [LoneDev6/addons-listing#39]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: TheElrosMC
title: Builder's Lab
content: Adds new furniture, tools, and items with custom mechanics using ItemsAdder Scripting
premium: false
icon: https://www.spigotmc.org/data/resource_icons/126/126233.jpg
banner: https://www.spigotmc.org/attachments/2025-06-20_22-39-jpg.902441/
time: 2025-06-20
links:
- https://www.spigotmc.org/resources/126233/
tags:
- items
- furniture
```
