### ISSUE TITLE
MedievalCraft Pack | 50+props

### ISSUE THREAD

**Issue by dorori123** [LoneDev6/addons-listing#40]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Neptune Services
title: MedievalCraft Pack
content: cozy medieval-themed ItemsAdder pack with 50+ custom props!
premium: true
icon: https://imgur.com/a/SQa4Gzb
banner: imgurlUrlHere
time: 2025-06-22
links:
- https://builtbybit.com/resources/medievalcraft-pack-50-itemsadder-items.68869/
tags:
- items
- medieval
- props
- decoration
```
