### ISSUE TITLE
NoDropX

### ISSUE THREAD

**Issue by iRedTea** [LoneDev6/addons-listing#8]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: itzRedTea
title: NoDropX
content: Save items from death!
premium: false
icon: https://cdn.modrinth.com/data/GvZhrpDY/14ae6c513db8ccaa3592e7359b7e967c7b4351a8_96.webp
banner:https://proxy.spigotmc.org/800e5322a61523c416b8ca455eda3e6ca92ef2a3/68747470733a2f2f692e696d6775722e636f6d2f504d784b5a45502e706e67
time: 2025-01-01
links:
- https://www.spigotmc.org/resources/nodropx.111485/
- https://modrinth.com/plugin/nodropx
tags:
- items
- misc
```
