### ISSUE TITLE
Color Portals

### ISSUE THREAD

**Issue by DinoJack250** [LoneDev6/addons-listing#9]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: DinoJack250
title: Color Portals
content: This is an ItemsAdder plugin addon. It requires the plugin ItemsAdder in order to use.This addon adds many colored portal variants to add more detail for custom portals! They cannot be crafted, and each color comes in 2 versions: EW: East/West NS: North/South

premium: false
icon: https://ibb.co/qLBTHH2R
banner: https://ibb.co/DfdNFrvD
time: 2025-01-01
links:
- https://www.spigotmc.org/resources/color-portals.124083/
tags:
- blocks
```
